### ISSUE TITLE
Make possible to use a different name for the app chunk

### ISSUE THREAD

**Issue by smax48** [aurelia/loader-webpack#20]
**I'm submitting a feature request**
- **Library Version:**
  1.0.2

**Please tell us about your environment:**
- **Operating System:**
  Windows 8.1
- **Node Version:**
  4.4.5
- **NPM Version:**
  3.9
- **JSPM OR Webpack AND Version**
  webpack 2.1.0-beta.21
- **Browser:**
  all 
- **Language:**
  TypeScript 2.0

**Current behavior:**

aurelia-loader-webpack always names the application chunk as 'app'.
So the output file name is always `'app.bundle[.<hash>].js'`
I found out that the current behaviour is driven by this code in loader-webpack:

```
        require.ensure([], require => {
          // if failed, try resolving via the context created by the plugin //
          const result = require('aurelia-loader-context/' + path);
          return this._getActualResult(result, resolve, reject);
        }, 'app');
```

**Expected/desired behavior:**

Allow to specify a different name for the app chunk.
If there is another way to achieve this, please let me know.

**What is the motivation / use case for changing the behavior?**

I need to use a different name for the output file that contains the app chunk. 
If using @easy-webpack based config (e.g. `@easy-webpack/config-env-development`), it is unclear how to change the output filename for the app bundle.

**Comment by niieani** [comment]
Thanks. I'm working on an update.

**Comment by EisenbergEffect** [comment]
@niieani How is this coming?

**Comment by niieani** [comment]
I've been working on splitting up the webpack plugin into 3-4 separate plugins / loaders, some usable even outside of Aurelia. 
It's a major rewrite, but it should solve 90% of all the issues currently open in the Webpack plugin and Webpack loader repos (and there are quite a few), including this one. 

Since the current plugin does so much already (some developers called it "magic"), it'll also be easier to understand and configure - there'll be a single tool for a single job, instead of the current "swiss-army-knife" approach.
This implementation will also make HMR and Server-Side loading (with Webpack) much easier.

I've been quite busy with other jobs lately, but that's about to change around this or next week if all goes well. I'd love some help; so @Vheissu, if you have some time and would like to help with the effort, let me know :).

**Comment by EisenbergEffect** [comment]
@niieani Thanks for the update. Please keep us posted. This is an important effort and your hard work is much appreciated.

**Comment by Vheissu** [comment]
@niieani I am definitely down to help out with this. I think it is a great idea. I am moving this weekend, but after that, I'll have a bit of time to help out.

**Comment by niieani** [comment]
Thanks for the offer @Vheissu. I'm still pretty busy myself, so we can dig into this when you're ready.

**Comment by niieani** [comment]
Fixed by https://github.com/aurelia/skeleton-navigation/pull/714
